List<String> cities = [];
List<String> pAKprovince = [
  "Islamabad",
  "punjab",
  "Sindh",
  "KPK",
  "Blochistan"
];

List<String> iCity = [
  'islamabad',
];
List<String> pCity = [
  "Ahmadpur East",
  "Ahmed Nager Chatha",
  "Arifwala",
  "Attock",
  "Baghalchur",
  "Bahawalnagar",
  "Bahawalpur",
  "Bhakkar",
  "Bhalwal",
  "Burewala",
  "Chakwal",
  'Chaubara',
  "Chichawatni",
  "Chiniot",
  "Chistian Mandi",
  'Choa Saidan Shah',
  'Chunian',
  'Daska',
  'Dhaular',
  'Dera Ghazi Khan',
  'Dipalpur',
  'Dinga',
  'Dunyapur',
  'Faisalabad',
  "Fatehjang",
  "Fort Abbas",
  "Gojra",
  "Gujar Khan",
  "Gujranwala",
  'Gujrat',
  'Hafizabad',
  'Haroonabad',
  'Hasilpur',
  'Isa Khel',
  'Jahania',
  'Jampur',
  'Jand',
  "Jaranwala",
  "Jatoi",
  "Jhang",
  "Sadar",
  "Jhelum",
  "Kalur",
  "Kot",
  "Kamalia",
  'Kamoke',
  "Karor",
  "Kasur",
  "Khanewal",
  "Khanpur",
  "Kharian",
  "Khushab",
  "Kot",
  "Addu",
  "Lahore",
  "Leiah",
  "Liaqatpur",
  "Lodhran",
  "Mailsi",
  "Mandi",
  "Burewala",
  "Mankera",
  "Mianwali",
  "Mithankot",
  "Multan",
  "Murree",
  "Muzaffargarh",
  "Narowaal",
  "Nurpur",
  "Okara",
  "Pakpattan",
  "Pasrur",
  "Phalla",
  "Pind Dadan Khan",
  "Qaidabad",
  "Rabwah",
  "Rahimyar",
  "Khan",
  "Rajanpur",
  "Rawalpindi",
  "Renala",
  "Khurd",
  "Rojhan",
  "Sadiqabad",
  "Sahiwal",
  "Samundri",
  "Sargodha",
  "Shahpur",
  "Shaher Sultan",
  "Shakargarh",
  "Sheikhupura",
  "Sialkot",
  "Talagang",
  "Taxila",
  "Toba Tek Singh",
  "Vihari",
  "Wah",
  "Wazirabad",
  "Yazman",
];

List<String> sCity = [
  "Karachi",
  "Hyderabad",
  "Sukkur",
  'Larkana',
  '	Nawabshah',
  'Mīrpur Khas',
  'Shikarpur',
  'Jacobabad',
  'Khairpur',
  'Dadu',
];
List<String> kCity = ["Peshawar", "Mardan", "Mingaora", "Kohat", "Abbottabad"];
List<String> bCity = [
  'Quetta',
  'Turbat',
  'Chaman',
  'Chaman',
  'Quetta',
  'Turbat',
  'Dera Murad Jamali',
  'Nasirabad'
];
