// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeLU-O9KSfWMoZsxw0kWa4XZ-pR8OO5DI',
    appId: '1:626109551689:web:7647588bfd037b9b9d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    authDomain: 'arrti-cf128.firebaseapp.com',
    storageBucket: 'arrti-cf128.appspot.com',
    measurementId: 'G-2JJBTTL2NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVBl0T42M8QreH9ng3-CC4U1Gsq8m-j4w',
    appId: '1:626109551689:android:61e9b731b5991be49d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    storageBucket: 'arrti-cf128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5mS7UmnrOVrJIB1aK0x1sfDDu5k3iOQ',
    appId: '1:626109551689:ios:27579b39898331019d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    storageBucket: 'arrti-cf128.appspot.com',
    androidClientId: '626109551689-mnatrm2ngqtp54alvq0q6o93dgn5ji1g.apps.googleusercontent.com',
    iosClientId: '626109551689-jfn40bpvpu5e8k441ptosmh5rdsavjb4.apps.googleusercontent.com',
    iosBundleId: 'com.AZainApps.apniMandi',
  );
}
